services:
  mongo:
    image: mongo:7
    container_name: ecommerce-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ecommerce
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
